apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:beipA8HmPD/apXEbz7UxxmRNctqchIM/3OIUQovEc9IFWFtl,iv:d/zXKVkNlvXApahseh7glf7w80J79SG+l8xAiKjLTHw=,tag:pkydLZOCPlu6ckWTuIlI6Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:7bcqSvFFS0SbGQgKzJ1ui4nzU7x4n/SuUaDBbvy3i4KRLDNKM9gJMU76LDZ1G+C7jp+LddA2beJtxxQqfnai6N5a71oPzKQ3EOwZKMENkNr0Nt+fDUvIIOjYZIuMSDtLy0GcXreLIeKozZ7jG2CH0TZ4NuJbjsWpu3arDne0bWuE93qJ51Yc8T9CjZwg8C9LwyRYzoZWfBuWkwdCEkW1wzANUAO35iKPfwOG3sz/NA==,iv:HfJVF7khZniwQgeFJmiSq0UPoKFoCt+4tvh6TzJuDmo=,tag:ZBi90DjeeQQbbVCjN1cfrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNEp6aHhlb2ZhUDh6UHpm
            T0k1aEN5UHhQN2RIOU5iTVFYSFFGSEI4Y1VnClUvRUVHWW9jTVFvSVFrYUE1V3l5
            dVpqNkRXUEd1VjhLdXRtdmJxVW1vZjQKLS0tIEg0NkNxZURiSC9pQ3RXTnUzcTFz
            a1hEeG5QT2ZuUHVucXFkOVdFK2tCWW8KPZWKVwaztP31cGPdkDlwNQ6nNayN4d4v
            HiSFk5RMnwz3+thP2yb5K1zRQ5ZkNqMumnLhGN/wmGschaXiO9G24Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T20:13:28Z"
    mac: ENC[AES256_GCM,data:fNTMtvDC2zWh4yRZ5rDeV6InfLIQzwxCUNnNylKkBt49To6L/wIfqdoIAYkZOtL0fYwo+LoaA7tCUZthrDaAi6iDc34TvPvMkolphMvO2Txs5kH/p/xU9TesXqMHYssRALGxA1EqrChuv+R4O4ElH3ng7hIkblEotSe4NOik9Y0=,iv:L4wTNSoSZvfpaH28wRDdqAOELXaJm4PTyY5bkj8rlh0=,tag:KJw9NvdwzzSiMtbVcMxxRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
