apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:EzdAG0csV0l4rcbQciNRiwSgSecTA6agV+sAiYZ68P/Pj0BE,iv:4BLgr8P/oe0hJk0Fne0U+raURZ30JdErNB3MIsSzYE0=,tag:SiqQfZ+Te/79Sr8jq/houg==,type:str]
    credentials.json: ENC[AES256_GCM,data:MazuhrKrUfZkBaYGRjEvQPxfhQjqJsQmsn9FyJ0KX4pFDPVW2/obJTnJeWQOPsVj4gi2rvG6O+j+IWG6kA2gBd6lKYE65c4RsG/bZ8rhIELkEjIlIFd/fzPgeC+Qc0UB9UVPjbn2e73An7WQpxDwCjdmJi+vfe0Al3IgkBhsvLIBmjpD5XdFFbLOFrSHHfZZe0iqeeE4U6aNy3VsWMip8AHk2wsgTajdc/rUQ0/rQUI8WA==,iv:r4C+rLZnOamjS/5sLd6OXxbN1o/Y7GliyY871NowbEk=,tag:oGuHK36UTO2C8yR1Idqg7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsS1A0NnJvQi9FRzl6YTJz
            cmhhKzBGcEdnak1aeHo2VEVsTkcvOUlBNkdzCnZjeDBMNWM3bU9SVTZkRy90d1Ex
            K2Y3N3Vhb1R4RlVRazRFWDV2cVFOaTgKLS0tIEhWY05iakJYbm9HSitsTFpxVjVy
            TFlsOWhCcExlVmhIa1dEN2pRbjJabW8KWnvAUXwLM7092OiIz/2R8CE9mNluvnT9
            wI5UIkurUJh9OQsx04lZK9uNOpv/f64nYtTapfGNinJNorNhipbdjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T08:49:20Z"
    mac: ENC[AES256_GCM,data:8SXFpyx/WDGygNw0sg1q5NvbipxDIQN2OsPNPCaE41vs/cWNIKLqMFh56xpJc4UY3Xz1VQo05omZjAGnSJKKz5lqgAQWCHHCoxywMbA6SUr23n7jZRr1RYD32mvD/UklsrRuuigKx8tOQ42Av0ijENwoqHzuV9Sbvbzj3XYWibk=,iv:/7+8l1jzv7pRylzkNDjs2w4P5Nz0OAKmHnHf3SAQxX4=,tag:C4rT8o2AeZooNp9sfHYpLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
