apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZNsgNBK82YUQfPSnAMb2jvE93DJ5feYtFG7PNvv5LLe06ERcILCJnQ==,iv:M4Bv7aiX4/0+4XZhg81L41YDrfOvZ5LoIJW/HNQ05w8=,tag:rP9F6GtDLtN94E6YT9EXEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTW5vVldXMmFnWUhXNFo4
            T0dydm5TM2tqM0RCaUdyazIrRnk5dDMvK3o0ClV6djZrN2JaUE1DRWg1WG1oQUhv
            eERVZ25sUk0wZDVEUmYwTW5TdU1lSFkKLS0tIEFIcS81bG9Kb1JpYzFiUWR0SGxj
            RUhqdWNUa0xjakszdTRNM2p6RnZFU3cK1R3sl89E+NX42MshzwDp0r7cG4p6BC/x
            pev8/NrHtoIPV115/ar/RppgBJ0gaWQGHwee0TPR2mCqu5vKdHXOYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T08:49:20Z"
    mac: ENC[AES256_GCM,data:70xsNcQnV8UY7dfCcNiLV17qJhAUUtBcuYxClEaFFWG7t3LJ4bcaluq+5yr+KskrCrWV0iodJI9ZcMpHgPW5FhYaV+b6oIisya6pmmrGScUI0NOMEfZTrYJkSf4jj0xBNROpb6bNGYRMaiKbWvGsZreQao+RZ2gR5ln49wmBXQ0=,iv:nI9t9hs8/kXL2FCrFgKm3LNlTyEB65nR5w9zyZHSSlY=,tag:cVA1vONyR/Y4PIY9g2fykA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
