apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:9TY7stPC5WL3y3RsQVDLvWm4j6OASm5UzsuUlxU0N8E6i6VLnBTGKiF9xUVm/T0BJekYakvtAsQBSwml6uaLizDLfJDLy/rbvuuax8QHUar48KUNeHHRrSImX8MMmg==,iv:nl5jMbs/4+QQrHgJJE+sNbNZrZ6uUuMCBgixDbZUKR4=,tag:U8frYIh/Wgbq+rtSh1XtUA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4RQSvwNi0/IIHe2/tCA=,iv:Sr+ez9FMRZonsFZErWzy2qJjzjihOvO7GYnxd+3yhZ4=,tag:vOqgSsNQeIYXaaEbeLwrJQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ceQH8E4xmkzt4X4HhePczYnz0Q==,iv:FrP6feOMd2xROK9oaEDhw1OWxd/kVSintc1JsPp91jE=,tag:rkPzk3y7w5drTzHpQT+Lmg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:j+xFQrjGv49GX19QSIXeYrEsjtR0jPnAUMFalgkWO2yv5Ul9,iv:D5aL6UZLFoeuuvDDCKCnmedU9S+yGtTk9Oihgc2XFfM=,tag:QDf3UrzYvWpXIoINtl+IBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOU5MNTFudDlLMDZqdlhB
            eWZHaXFsNlFLRlpKeVBpRmxuNHdVbUNBSHdRCmNVckpYRnFZK29veGt5Z2o4dXVY
            NTJCVVNvQVcxczZFbVhLRWRyWjZoVmMKLS0tIExwRWlCc1QreHRhSVNzR3dhaERv
            azBQZW1IWmlIVHZES0s0ODIrN2FhSFEKLv7+Pptx2iN01YILIvZnYpR1CXbLjLqB
            AT8vCkeX+2OcQvPBiFUaqGqj4imddE7Q/PC0Sh0MjTP9jyGKTnML1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T08:28:41Z"
    mac: ENC[AES256_GCM,data:z0uNHoaQTHV/FopBWt+tdPGQbQJlJpIhvJYqq2qb0PgIYbtkrWUVpDQbe+i2hUrlA9/jwX04js4LRn+atBN/u6tresC9fsEKc1K6xPfe90guclI4f7o8xHOLqFWW0CQD3e2rCVF8qdJr4vZ/a2ozqxy9VHVznx1cNjDegqBAuww=,iv:ltTwam9jKQA7wkuCOUv0Ldr6HJArizojclZuMBWHuiA=,tag:N449Q03am7NftRNTaOSb7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
